name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      - name: Cypress action
        with: # Set Cypress credentials secret as an input
          credentials: ${{ secrets.CYPRESS_KEY }}
        env: # Or as an environment variable
          credentials: ${{ secrets.CYPRESS_KEY }}
